#!/usr/bin/env bash
# Create a custom error page

sudo apt-get update
sudo apt-get install -y nginx


echo "Hello World!" | sudo tee /var/www/html/index.html


new_file="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/TrudyB-T permanent;"
sudo sed -i "s/server_name _;/$new_file/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_file="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_file/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
