#!/usr/bin/env bash
# manages manage_my_process.



if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    printf "manage_my_process started\n"
elif [ "${1}" == "stop" ]
then
    printf "manage_my_process stopped\n"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    printf "manage_my_process restarted\n"
else
    printf "Usage: manage_my_process {start|stop|restart}\n"
fi
