#!/usr/bin/env bash
#displays the content of the file /etc/passwd

while IFS=':' read -r username password uid gid uid_info home_dir shell; do
  echo "The user $username is part of the $gid gang,"\
  "lives in $home_dir and rides $shell."\
  "$uid's place is protected by the passcode $password,"\
  "more info about the user here: $uid_info"
done < "/etc/passwd"
