#!/usr/bin/env bash
#displays Best School 10 times except 9th iteration
var='Best School'
vari='Hi'
min=1
max=12
ite=10

while [ "$min" -lt "$max" ]; do
	if [ "$min" -eq "$ite" ]; then
		echo $vari
	else
		echo "$var"

	fi
	((min++))
done
