#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
var='Best School'
vari='good luck'
va='bad luck'
min=1
max=11
ite=4
iter=8

while [ "$min" -lt "$max" ]; do
	if [ "$min" -eq "$ite" ]; then
		echo "$va"
	elif [ "$min" -eq "$iter" ]; then
		echo "$vari"
	else
		echo "$var"

	fi
	((min++))
done
