#!/usr/bin/env bash
#Gracefully reloads Gunicorn.


mapfile -t gunicorn_pids < <(pgrep gunicorn)

for pid in "${gunicorn_pids[@]}"; do
    kill -HUP "$pid"
    echo "Sent HUP signal to Gunicorn process with PID $pid."
done
