#!/usr/bin/env bash
# Gracefully reloads Gunicorn.


PID=$( sudo pgrep -f 'gunicorn --bind')

if [ -z "$PID" ]
then
  echo "Gunicorn is not running."
else
   sudo kill -HUP "$PID"
  echo "Gunicorn has been gracefully reloaded."
fi
